name: Build APK with Buildozer

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 \
            build-essential libffi-dev libssl-dev

      - name: Install Python Packages
        run: |
          pip install --upgrade pip wheel
          pip install buildozer kivy

      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Set Build Directory
        run: |
          mkdir -p $HOME/buildozer_build
          echo "BUILD_DIR=$HOME/buildozer_build" >> $GITHUB_ENV

      - name: Build APK (with verbose logs)
        run: |
          buildozer --verbose android debug 2>&1 | tee build.log
        env:
          ACCEPT_ALL_LICENSES: y  # Auto-accept Android licenses

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk

      - name: Upload Logs if Failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log
